name: Sass CI

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 10
          submodules: 10

      - name: Install Dependencies
        run: |
          cd static
          npm install

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: ./static/sass/styles.scss
          destination: ./static/css/styles.css
